### PR TITLE
Add Oleg

### PR DESCRIPTION
**Pull request by mietek**
Requesting permission to transfer ownership of the https://github.com/mietek/oleg repository to the museum.

### CODE REVIEW

**Comment by kohlhase** [comment]
thanks a lot. 
I think I saw that you were asking for permission to add oleg to the theorem prover museum, but I cannot find anything there yet. 
I am very happy to let you do that, but I need a handle. Could you re-send that. 
Otherwise I can just make a repository and give admin to you.

**Comment by mietek** [comment]
My handle is “mietek”. If you add me as a contributor with the right to create public repositories, then I will be able to make the transfer.

**Comment by kohlhase** [comment]
I made a repository and gave you admin, that should be sufficient, no?

**Comment by mietek** [comment]
Yes, this works as well. Thank you. Oleg is up at https://github.com/theoremprover-museum/oleg

**Pull request merged**
